### ISSUE TITLE
Error in importing module

### ISSUE THREAD

**Issue by MeHelmy** [aquaskyline/Clair#1]
Command used: `python ./clair.py callVarBam`
Error:

>  return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 985, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 952, in _find_and_load_unlocked
> ImportError: No module named 'clair.callVarBam'; 'clair' is not a package .

**Comment by aquaskyline** [comment]
@MeHelmy fixed.
